# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160306_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='link',
        ),
    ]
