# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160306_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='link',
            new_name='url',
        ),
    ]
