# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160306_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_start',
            field=models.DateField(null=True),
        ),
    ]
