# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160417_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
