# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160307_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
