# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160425_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='place_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='place_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
