# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160427_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='place_latitude',
        ),
        migrations.RemoveField(
            model_name='post',
            name='place_longitude',
        ),
    ]
