# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160427_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='geo_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
