# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-02 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160502_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='geom',
            new_name='geometry',
        ),
    ]
