# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-02 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160502_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='geometry',
            new_name='geom',
        ),
    ]
