# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-02 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20160502_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
