# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_trip_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='geo_json',
        ),
        migrations.RemoveField(
            model_name='post',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_favourite',
        ),
        migrations.RemoveField(
            model_name='post',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='post',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='lon',
        ),
        migrations.AddField(
            model_name='post',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
