# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20160505_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coordinates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='coordinates',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
