# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20160510_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
