# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20160510_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
