# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20160514_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
