# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-13 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20160514_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.SlugField(max_length=20),
        ),
    ]
